// Array of image data with Cloudinary public IDs and grid positioning
const imagesPublicIds = [
  'fashion-red_new_epiv7w',
  'inirior-living_6_new_di69xt',
  'intiroir-living5_new_yc6yjt',
  'interioir-office2_new_umnlzq',
  'intirioir-bedroom_new_jg1a4u',
  'interioir-wall_new_mquymp',
  'interioir-office4_new_gs4vfi',
  'intirior-kitchen6_new_vrf1mj',
  'intirior-bedroom3_new_qxqmox',
  'intiori-kitchen7_new_ymkf2v',
  'intirior-kitchen_new_f34l3c',
  'intirior-living_new_jghr6m',
  'intirooir-door_new_ebluam',
  'product-beauty4.webp7_new_et5fjt',
  'product-beauty4.webp5_new_boyzt0',
  'product-beauty-3_new_kzuera',
  'product-beauty2_new_cua3k6',
  'product-beauty4.webp6_new_emut1d',
  'product-beauty4_new_dbcy48',
  'product_new_t5agfb',
  'product-tech_new_uxcomw',
  'yoga_new_b1jsar',
  'product-beauty7_new_xpy5fo',
  'wooden_chair_new_okdyzv',
  'product-beauty5_new_twx0er',
  'product-beauty6_new_ctnjfw',
  'interioir_u3f76c',
  'interior-kitchen_jieg4d',
  'immo-building_a0f80p',
  'immo-hotel_lwdq5r',
  'office_d08wuu',
  'immo-house_enbomh',
  'fashion-clothing7_new_dinlr3',
  'aeshtethics-beach4_new_unumxp',
  'aeshtetics-girls_new_vcpolo',
  'aesthethics-colors6_new_vyybo9',
  'aeshtetics-palms_new_pwohsg',
  'aeshtetics-colors6_new_rvtsqb',
  'aestheic-moon_new_j16mos',
  'aeshtetics-shell3_new_uv1igv',
  'aesthetic-beach_new_zupwjt',
  'aesthethics-shell5_new_mg6jxg',
  'aesthethics-palm4_new_hm1pt0',
  'aesthetic-colors2_new_lwhg6o',
  'aesthetics-palms2_new_e0skhg',
  'aesthetics-girls3_new_bbg1ax',
  'aesthetic-beauty_new_msguuc',
  'aesthetics-colors4_new_cfz9pm',
  'aesthetic-colors_new_xm0y15',
  'aesthetic-oil_new_skbkqr',
  'aesthetic-future_new_u8wfx0',
  'aesthetic-design_new_earenr',
  'aesthetics-beauty4_new_tdmlll',
  'aesthetics-colors5_new_hauzc7',
  'aesthetics-shell_new_mbqcbs',
  'aesthetics-shell6_new_lqgtbz',
  'beach-paddle_new_fxf3pg',
  'beach_new_uncd4l',
  'aethetics-portrait_new_bcp7xz',
  'building-jungle_new_a5dof6',
  'beach4_new_dvd9qu',
  'beach2_new_blefmr',
  'building-villa_new_h4dsbv',
  'beauty-product-2_new_qnr6je',
  'building-office3_new_atryhm',
  'building-future_new_mmbbcl',
  'fashion-clothing9_new_ritijr',
  'interioir-kitchen_new_cv5xba',
  'fashion-person_new_unrvzr',
  'immo-oofice_new_r6shti',
  'fashion-clothing6_new_b8jjlp',
  'furniturer_new_omjgyb',
  'fashion-clothing5_new_ey2i9k',
  'fashion-clothing8_new_afgksh',
  'fashion-clothing3_new_piwu7g',
  'fashion-clothing_new_pv3jqw',
  'fashion-clothing4_new_a4kabz',
  'building-villa3_new_raystv',
  'building-villa5_new_tf0jwq',
  'building-villa2_new_jsphck',
  'building-treehouse_new_i1eico',
  'building-jungle3_new_aksesw',
  'building-future2_new_b00ebe',
  'beauty-product_new_nvod2f',
];

// Shuffle function using Fisher-Yates algorithm
function shuffleArray(array) {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

// Create a randomly shuffled version of the public IDs
const shuffledImagesPublicIds = shuffleArray(imagesPublicIds);

// Manually positioned gallery images for optimal spacing and layout
export const galleryImages = [
  {
    id: 1,
    publicId: shuffledImagesPublicIds[0],
    alt: 'Gallery image 1',
    gridColumn: '1/3',
    gridRow: '1',
    aspectRatio: '3/2',
    dataSpeed: '1.0',
  },
  {
    id: 2,
    publicId: shuffledImagesPublicIds[1],
    alt: 'Gallery image 2',
    gridColumn: '4/6',
    gridRow: '1',
    aspectRatio: '1/1',
    dataSpeed: '0.9',
  },
  {
    id: 3,
    publicId: shuffledImagesPublicIds[2],
    alt: 'Gallery image 3',
    gridColumn: '7/9',
    gridRow: '2',
    aspectRatio: '2/3',
    dataSpeed: '1.1',
  },
  {
    id: 4,
    publicId: shuffledImagesPublicIds[3],
    alt: 'Gallery image 4',
    gridColumn: '2/4',
    gridRow: '4',
    aspectRatio: '16/9',
    dataSpeed: '1.2',
  },
  {
    id: 5,
    publicId: shuffledImagesPublicIds[4],
    alt: 'Gallery image 5',
    gridColumn: '5/7',
    gridRow: '3',
    aspectRatio: '4/3',
    dataSpeed: '0.8',
  },
  {
    id: 6,
    publicId: shuffledImagesPublicIds[5],
    alt: 'Gallery image 6',
    gridColumn: '1/4',
    gridRow: '6',
    aspectRatio: '3/1',
    dataSpeed: '1.0',
  },
  {
    id: 7,
    publicId: shuffledImagesPublicIds[6],
    alt: 'Gallery image 7',
    gridColumn: '6/8',
    gridRow: '5',
    aspectRatio: '1/2',
    dataSpeed: '0.9',
  },
  {
    id: 8,
    publicId: shuffledImagesPublicIds[7],
    alt: 'Gallery image 8',
    gridColumn: '2/5',
    gridRow: '8',
    aspectRatio: '3/2',
    dataSpeed: '1.1',
  },
  {
    id: 9,
    publicId: shuffledImagesPublicIds[8],
    alt: 'Gallery image 9',
    gridColumn: '7/9',
    gridRow: '7',
    aspectRatio: '9/16',
    dataSpeed: '1.2',
  },
  {
    id: 10,
    publicId: shuffledImagesPublicIds[9],
    alt: 'Gallery image 10',
    gridColumn: '1/3',
    gridRow: '10',
    aspectRatio: '1/1',
    dataSpeed: '0.8',
  },
  {
    id: 11,
    publicId: shuffledImagesPublicIds[10],
    alt: 'Gallery image 11',
    gridColumn: '4/7',
    gridRow: '9',
    aspectRatio: '2/1',
    dataSpeed: '1.0',
  },
  {
    id: 12,
    publicId: shuffledImagesPublicIds[11],
    alt: 'Gallery image 12',
    gridColumn: '6/8',
    gridRow: '11',
    aspectRatio: '3/4',
    dataSpeed: '0.9',
  },
  {
    id: 13,
    publicId: shuffledImagesPublicIds[12],
    alt: 'Gallery image 13',
    gridColumn: '2/4',
    gridRow: '13',
    aspectRatio: '1/2',
    dataSpeed: '1.1',
  },
  {
    id: 14,
    publicId: shuffledImagesPublicIds[13],
    alt: 'Gallery image 14',
    gridColumn: '5/7',
    gridRow: '12',
    aspectRatio: '1/1',
    dataSpeed: '1.2',
  },
  {
    id: 15,
    publicId: shuffledImagesPublicIds[14],
    alt: 'Gallery image 15',
    gridColumn: '1/3',
    gridRow: '15',
    aspectRatio: '3/2',
    dataSpeed: '0.8',
  },
  {
    id: 16,
    publicId: shuffledImagesPublicIds[15],
    alt: 'Gallery image 16',
    gridColumn: '7/9',
    gridRow: '14',
    aspectRatio: '4/3',
    dataSpeed: '1.0',
  },
  {
    id: 17,
    publicId: shuffledImagesPublicIds[16],
    alt: 'Gallery image 17',
    gridColumn: '3/6',
    gridRow: '16',
    aspectRatio: '16/9',
    dataSpeed: '0.9',
  },
  {
    id: 18,
    publicId: shuffledImagesPublicIds[17],
    alt: 'Gallery image 18',
    gridColumn: '6/8',
    gridRow: '17',
    aspectRatio: '2/3',
    dataSpeed: '1.1',
  },
  {
    id: 19,
    publicId: shuffledImagesPublicIds[18],
    alt: 'Gallery image 19',
    gridColumn: '1/4',
    gridRow: '19',
    aspectRatio: '3/1',
    dataSpeed: '1.2',
  },
  {
    id: 20,
    publicId: shuffledImagesPublicIds[19],
    alt: 'Gallery image 20',
    gridColumn: '5/7',
    gridRow: '18',
    aspectRatio: '1/1',
    dataSpeed: '0.8',
  },
  {
    id: 21,
    publicId: shuffledImagesPublicIds[20],
    alt: 'Gallery image 21',
    gridColumn: '2/4',
    gridRow: '21',
    aspectRatio: '9/16',
    dataSpeed: '1.0',
  },
  {
    id: 22,
    publicId: shuffledImagesPublicIds[21],
    alt: 'Gallery image 22',
    gridColumn: '7/9',
    gridRow: '20',
    aspectRatio: '3/2',
    dataSpeed: '0.9',
  },
  {
    id: 23,
    publicId: shuffledImagesPublicIds[22],
    alt: 'Gallery image 23',
    gridColumn: '4/6',
    gridRow: '22',
    aspectRatio: '1/2',
    dataSpeed: '1.1',
  },
  {
    id: 24,
    publicId: shuffledImagesPublicIds[23],
    alt: 'Gallery image 24',
    gridColumn: '1/3',
    gridRow: '24',
    aspectRatio: '3/4',
    dataSpeed: '1.2',
  },
  {
    id: 25,
    publicId: shuffledImagesPublicIds[24],
    alt: 'Gallery image 25',
    gridColumn: '6/8',
    gridRow: '23',
    aspectRatio: '2/1',
    dataSpeed: '0.8',
  },
  {
    id: 26,
    publicId: shuffledImagesPublicIds[25],
    alt: 'Gallery image 26',
    gridColumn: '3/5',
    gridRow: '25',
    aspectRatio: '1/1',
    dataSpeed: '1.0',
  },
  {
    id: 27,
    publicId: shuffledImagesPublicIds[26],
    alt: 'Gallery image 27',
    gridColumn: '7/9',
    gridRow: '26',
    aspectRatio: '4/3',
    dataSpeed: '0.9',
  },
  {
    id: 28,
    publicId: shuffledImagesPublicIds[27],
    alt: 'Gallery image 28',
    gridColumn: '1/4',
    gridRow: '28',
    aspectRatio: '3/1',
    dataSpeed: '1.1',
  },
  {
    id: 29,
    publicId: shuffledImagesPublicIds[28],
    alt: 'Gallery image 29',
    gridColumn: '5/7',
    gridRow: '27',
    aspectRatio: '16/9',
    dataSpeed: '1.2',
  },
  {
    id: 30,
    publicId: shuffledImagesPublicIds[29],
    alt: 'Gallery image 30',
    gridColumn: '2/4',
    gridRow: '30',
    aspectRatio: '2/3',
    dataSpeed: '0.8',
  },
  {
    id: 31,
    publicId: shuffledImagesPublicIds[30],
    alt: 'Gallery image 31',
    gridColumn: '6/8',
    gridRow: '29',
    aspectRatio: '3/2',
    dataSpeed: '1.0',
  },
  {
    id: 32,
    publicId: shuffledImagesPublicIds[31],
    alt: 'Gallery image 32',
    gridColumn: '4/6',
    gridRow: '31',
    aspectRatio: '1/2',
    dataSpeed: '0.9',
  },
  {
    id: 33,
    publicId: shuffledImagesPublicIds[32],
    alt: 'Gallery image 33',
    gridColumn: '1/3',
    gridRow: '33',
    aspectRatio: '1/1',
    dataSpeed: '1.1',
  },
  {
    id: 34,
    publicId: shuffledImagesPublicIds[33],
    alt: 'Gallery image 34',
    gridColumn: '7/9',
    gridRow: '32',
    aspectRatio: '9/16',
    dataSpeed: '1.2',
  },
  {
    id: 35,
    publicId: shuffledImagesPublicIds[34],
    alt: 'Gallery image 35',
    gridColumn: '3/5',
    gridRow: '34',
    aspectRatio: '3/4',
    dataSpeed: '0.8',
  },
  {
    id: 36,
    publicId: shuffledImagesPublicIds[35],
    alt: 'Gallery image 36',
    gridColumn: '5/8',
    gridRow: '35',
    aspectRatio: '2/1',
    dataSpeed: '1.0',
  },
  {
    id: 37,
    publicId: shuffledImagesPublicIds[36],
    alt: 'Gallery image 37',
    gridColumn: '1/4',
    gridRow: '37',
    aspectRatio: '3/1',
    dataSpeed: '0.9',
  },
  {
    id: 38,
    publicId: shuffledImagesPublicIds[37],
    alt: 'Gallery image 38',
    gridColumn: '6/8',
    gridRow: '36',
    aspectRatio: '1/1',
    dataSpeed: '1.1',
  },
  {
    id: 39,
    publicId: shuffledImagesPublicIds[38],
    alt: 'Gallery image 39',
    gridColumn: '2/4',
    gridRow: '39',
    aspectRatio: '4/3',
    dataSpeed: '1.2',
  },
  {
    id: 40,
    publicId: shuffledImagesPublicIds[39],
    alt: 'Gallery image 40',
    gridColumn: '7/9',
    gridRow: '38',
    aspectRatio: '16/9',
    dataSpeed: '0.8',
  },
  {
    id: 41,
    publicId: shuffledImagesPublicIds[40],
    alt: 'Gallery image 41',
    gridColumn: '4/6',
    gridRow: '40',
    aspectRatio: '2/3',
    dataSpeed: '1.0',
  },
  {
    id: 42,
    publicId: shuffledImagesPublicIds[41],
    alt: 'Gallery image 42',
    gridColumn: '1/3',
    gridRow: '42',
    aspectRatio: '3/2',
    dataSpeed: '0.9',
  },
  {
    id: 43,
    publicId: shuffledImagesPublicIds[42],
    alt: 'Gallery image 43',
    gridColumn: '5/7',
    gridRow: '41',
    aspectRatio: '1/2',
    dataSpeed: '1.1',
  },
  {
    id: 44,
    publicId: shuffledImagesPublicIds[43],
    alt: 'Gallery image 44',
    gridColumn: '6/8',
    gridRow: '43',
    aspectRatio: '1/1',
    dataSpeed: '1.2',
  },
  {
    id: 45,
    publicId: shuffledImagesPublicIds[44],
    alt: 'Gallery image 45',
    gridColumn: '2/5',
    gridRow: '45',
    aspectRatio: '3/1',
    dataSpeed: '0.8',
  },
  {
    id: 46,
    publicId: shuffledImagesPublicIds[45],
    alt: 'Gallery image 46',
    gridColumn: '7/9',
    gridRow: '44',
    aspectRatio: '9/16',
    dataSpeed: '1.0',
  },
  {
    id: 47,
    publicId: shuffledImagesPublicIds[46],
    alt: 'Gallery image 47',
    gridColumn: '1/3',
    gridRow: '47',
    aspectRatio: '3/4',
    dataSpeed: '0.9',
  },
  {
    id: 48,
    publicId: shuffledImagesPublicIds[47],
    alt: 'Gallery image 48',
    gridColumn: '4/6',
    gridRow: '46',
    aspectRatio: '2/1',
    dataSpeed: '1.1',
  },
  {
    id: 49,
    publicId: shuffledImagesPublicIds[48],
    alt: 'Gallery image 49',
    gridColumn: '6/8',
    gridRow: '48',
    aspectRatio: '4/3',
    dataSpeed: '1.2',
  },
  {
    id: 50,
    publicId: shuffledImagesPublicIds[49],
    alt: 'Gallery image 50',
    gridColumn: '2/4',
    gridRow: '50',
    aspectRatio: '16/9',
    dataSpeed: '0.8',
  },
  {
    id: 51,
    publicId: shuffledImagesPublicIds[50],
    alt: 'Gallery image 51',
    gridColumn: '1/4',
    gridRow: '52',
    aspectRatio: '3/1',
    dataSpeed: '1.0',
  },
  {
    id: 52,
    publicId: shuffledImagesPublicIds[51],
    alt: 'Gallery image 52',
    gridColumn: '5/7',
    gridRow: '49',
    aspectRatio: '1/1',
    dataSpeed: '0.9',
  },
  {
    id: 53,
    publicId: shuffledImagesPublicIds[52],
    alt: 'Gallery image 53',
    gridColumn: '7/9',
    gridRow: '51',
    aspectRatio: '2/3',
    dataSpeed: '1.1',
  },
  {
    id: 54,
    publicId: shuffledImagesPublicIds[53],
    alt: 'Gallery image 54',
    gridColumn: '3/5',
    gridRow: '53',
    aspectRatio: '3/2',
    dataSpeed: '1.2',
  },
  {
    id: 55,
    publicId: shuffledImagesPublicIds[54],
    alt: 'Gallery image 55',
    gridColumn: '1/3',
    gridRow: '55',
    aspectRatio: '1/2',
    dataSpeed: '0.8',
  },
  {
    id: 56,
    publicId: shuffledImagesPublicIds[55],
    alt: 'Gallery image 56',
    gridColumn: '6/8',
    gridRow: '54',
    aspectRatio: '3/4',
    dataSpeed: '1.0',
  },
  {
    id: 57,
    publicId: shuffledImagesPublicIds[56],
    alt: 'Gallery image 57',
    gridColumn: '4/6',
    gridRow: '56',
    aspectRatio: '1/1',
    dataSpeed: '0.9',
  },
  {
    id: 58,
    publicId: shuffledImagesPublicIds[57],
    alt: 'Gallery image 58',
    gridColumn: '2/5',
    gridRow: '58',
    aspectRatio: '3/1',
    dataSpeed: '1.1',
  },
  {
    id: 59,
    publicId: shuffledImagesPublicIds[58],
    alt: 'Gallery image 59',
    gridColumn: '7/9',
    gridRow: '57',
    aspectRatio: '9/16',
    dataSpeed: '1.2',
  },
  {
    id: 60,
    publicId: shuffledImagesPublicIds[59],
    alt: 'Gallery image 60',
    gridColumn: '1/3',
    gridRow: '60',
    aspectRatio: '2/1',
    dataSpeed: '0.8',
  },
  {
    id: 61,
    publicId: shuffledImagesPublicIds[60],
    alt: 'Gallery image 61',
    gridColumn: '5/7',
    gridRow: '59',
    aspectRatio: '4/3',
    dataSpeed: '1.0',
  },
  {
    id: 62,
    publicId: shuffledImagesPublicIds[61],
    alt: 'Gallery image 62',
    gridColumn: '3/5',
    gridRow: '61',
    aspectRatio: '16/9',
    dataSpeed: '0.9',
  },
  {
    id: 63,
    publicId: shuffledImagesPublicIds[62],
    alt: 'Gallery image 63',
    gridColumn: '6/8',
    gridRow: '62',
    aspectRatio: '2/3',
    dataSpeed: '1.1',
  },
  {
    id: 64,
    publicId: shuffledImagesPublicIds[63],
    alt: 'Gallery image 64',
    gridColumn: '1/4',
    gridRow: '64',
    aspectRatio: '3/1',
    dataSpeed: '1.2',
  },
  {
    id: 65,
    publicId: shuffledImagesPublicIds[64],
    alt: 'Gallery image 65',
    gridColumn: '7/9',
    gridRow: '63',
    aspectRatio: '3/2',
    dataSpeed: '0.8',
  },
  {
    id: 66,
    publicId: shuffledImagesPublicIds[65],
    alt: 'Gallery image 66',
    gridColumn: '4/6',
    gridRow: '65',
    aspectRatio: '1/2',
    dataSpeed: '1.0',
  },
  {
    id: 67,
    publicId: shuffledImagesPublicIds[66],
    alt: 'Gallery image 67',
    gridColumn: '2/4',
    gridRow: '67',
    aspectRatio: '1/1',
    dataSpeed: '0.9',
  },
  {
    id: 68,
    publicId: shuffledImagesPublicIds[67],
    alt: 'Gallery image 68',
    gridColumn: '5/7',
    gridRow: '66',
    aspectRatio: '3/4',
    dataSpeed: '1.1',
  },
  {
    id: 69,
    publicId: shuffledImagesPublicIds[68],
    alt: 'Gallery image 69',
    gridColumn: '1/3',
    gridRow: '69',
    aspectRatio: '9/16',
    dataSpeed: '1.2',
  },
  {
    id: 70,
    publicId: shuffledImagesPublicIds[69],
    alt: 'Gallery image 70',
    gridColumn: '6/8',
    gridRow: '68',
    aspectRatio: '2/1',
    dataSpeed: '0.8',
  },
  {
    id: 71,
    publicId: shuffledImagesPublicIds[70],
    alt: 'Gallery image 71',
    gridColumn: '3/5',
    gridRow: '70',
    aspectRatio: '4/3',
    dataSpeed: '1.0',
  },
  {
    id: 72,
    publicId: shuffledImagesPublicIds[71],
    alt: 'Gallery image 72',
    gridColumn: '7/9',
    gridRow: '71',
    aspectRatio: '16/9',
    dataSpeed: '0.9',
  },
  {
    id: 73,
    publicId: shuffledImagesPublicIds[72],
    alt: 'Gallery image 73',
    gridColumn: '1/4',
    gridRow: '73',
    aspectRatio: '3/1',
    dataSpeed: '1.1',
  },
  {
    id: 74,
    publicId: shuffledImagesPublicIds[73],
    alt: 'Gallery image 74',
    gridColumn: '4/6',
    gridRow: '72',
    aspectRatio: '2/3',
    dataSpeed: '1.2',
  },
  {
    id: 75,
    publicId: shuffledImagesPublicIds[74],
    alt: 'Gallery image 75',
    gridColumn: '6/8',
    gridRow: '74',
    aspectRatio: '3/2',
    dataSpeed: '0.8',
  },
  {
    id: 76,
    publicId: shuffledImagesPublicIds[75],
    alt: 'Gallery image 76',
    gridColumn: '2/4',
    gridRow: '76',
    aspectRatio: '1/2',
    dataSpeed: '1.0',
  },
  {
    id: 77,
    publicId: shuffledImagesPublicIds[76],
    alt: 'Gallery image 77',
    gridColumn: '5/7',
    gridRow: '75',
    aspectRatio: '1/1',
    dataSpeed: '0.9',
  },
  {
    id: 78,
    publicId: shuffledImagesPublicIds[77],
    alt: 'Gallery image 78',
    gridColumn: '1/3',
    gridRow: '78',
    aspectRatio: '3/4',
    dataSpeed: '1.1',
  },
  {
    id: 79,
    publicId: shuffledImagesPublicIds[78],
    alt: 'Gallery image 79',
    gridColumn: '7/9',
    gridRow: '77',
    aspectRatio: '2/1',
    dataSpeed: '1.2',
  },
  {
    id: 80,
    publicId: shuffledImagesPublicIds[79],
    alt: 'Gallery image 80',
    gridColumn: '3/5',
    gridRow: '79',
    aspectRatio: '4/3',
    dataSpeed: '0.8',
  },
  {
    id: 81,
    publicId: shuffledImagesPublicIds[0],
    alt: 'Gallery image 81',
    gridColumn: '6/8',
    gridRow: '80',
    aspectRatio: '1/1',
    dataSpeed: '1.0',
  },
  {
    id: 82,
    publicId: shuffledImagesPublicIds[1],
    alt: 'Gallery image 82',
    gridColumn: '1/4',
    gridRow: '82',
    aspectRatio: '3/1',
    dataSpeed: '0.9',
  },
  {
    id: 83,
    publicId: shuffledImagesPublicIds[2],
    alt: 'Gallery image 83',
    gridColumn: '4/6',
    gridRow: '81',
    aspectRatio: '2/3',
    dataSpeed: '1.1',
  },
  {
    id: 84,
    publicId: shuffledImagesPublicIds[3],
    alt: 'Gallery image 84',
    gridColumn: '7/9',
    gridRow: '83',
    aspectRatio: '3/2',
    dataSpeed: '1.2',
  },
];

// Mobile gallery images optimized for 4-column layout
export const galleryImagesMobile = [
  {
    id: 1,
    publicId: shuffledImagesPublicIds[0],
    alt: 'Gallery image 1',
    gridColumn: '1/3',
    gridRow: '1',
    aspectRatio: '3/2',
    dataSpeed: '1.0',
  },
  {
    id: 2,
    publicId: shuffledImagesPublicIds[1],
    alt: 'Gallery image 2',
    gridColumn: '3/4',
    gridRow: '2',
    aspectRatio: '1/1',
    dataSpeed: '0.9',
  },
  {
    id: 3,
    publicId: shuffledImagesPublicIds[2],
    alt: 'Gallery image 3',
    gridColumn: '1/2',
    gridRow: '4',
    aspectRatio: '1/1',
    dataSpeed: '1.1',
  },
  {
    id: 4,
    publicId: shuffledImagesPublicIds[3],
    alt: 'Gallery image 4',
    gridColumn: '2/4',
    gridRow: '5',
    aspectRatio: '2/1',
    dataSpeed: '1.2',
  },
  {
    id: 5,
    publicId: shuffledImagesPublicIds[4],
    alt: 'Gallery image 5',
    gridColumn: '3/4',
    gridRow: '6',
    aspectRatio: '1/1',
    dataSpeed: '0.8',
  },
  {
    id: 6,
    publicId: shuffledImagesPublicIds[5],
    alt: 'Gallery image 6',
    gridColumn: '1/3',
    gridRow: '8',
    aspectRatio: '1/1',
    dataSpeed: '1.0',
  },
  {
    id: 7,
    publicId: shuffledImagesPublicIds[6],
    alt: 'Gallery image 7',
    gridColumn: '2/4',
    gridRow: '9',
    aspectRatio: '1/1',
    dataSpeed: '0.9',
  },
  {
    id: 8,
    publicId: shuffledImagesPublicIds[7],
    alt: 'Gallery image 8',
    gridColumn: '1/2',
    gridRow: '10',
    aspectRatio: '1/1',
    dataSpeed: '1.1',
  },
  {
    id: 9,
    publicId: shuffledImagesPublicIds[8],
    alt: 'Gallery image 9',
    gridColumn: '2/4',
    gridRow: '12',
    aspectRatio: '2/1',
    dataSpeed: '1.2',
  },
  {
    id: 10,
    publicId: shuffledImagesPublicIds[9],
    alt: 'Gallery image 10',
    gridColumn: '3/4',
    gridRow: '13',
    aspectRatio: '1/1',
    dataSpeed: '0.8',
  },
  {
    id: 11,
    publicId: shuffledImagesPublicIds[10],
    alt: 'Gallery image 11',
    gridColumn: '1/3',
    gridRow: '14',
    aspectRatio: '1/1',
    dataSpeed: '1.0',
  },
  {
    id: 12,
    publicId: shuffledImagesPublicIds[11],
    alt: 'Gallery image 12',
    gridColumn: '1/2',
    gridRow: '15',
    aspectRatio: '1/1',
    dataSpeed: '0.9',
  },
  {
    id: 13,
    publicId: shuffledImagesPublicIds[12],
    alt: 'Gallery image 13',
    gridColumn: '1/4',
    gridRow: '17',
    aspectRatio: '3/1',
    dataSpeed: '1.1',
  },
  {
    id: 14,
    publicId: shuffledImagesPublicIds[13],
    alt: 'Gallery image 14',
    gridColumn: '2/3',
    gridRow: '18',
    aspectRatio: '1/1',
    dataSpeed: '1.2',
  },
  {
    id: 15,
    publicId: shuffledImagesPublicIds[14],
    alt: 'Gallery image 15',
    gridColumn: '3/4',
    gridRow: '20',
    aspectRatio: '1/1',
    dataSpeed: '0.8',
  },
  {
    id: 16,
    publicId: shuffledImagesPublicIds[15],
    alt: 'Gallery image 16',
    gridColumn: '1/3',
    gridRow: '21',
    aspectRatio: '2/1',
    dataSpeed: '1.0',
  },
  {
    id: 17,
    publicId: shuffledImagesPublicIds[16],
    alt: 'Gallery image 17',
    gridColumn: '3/4',
    gridRow: '22',
    aspectRatio: '1/1',
    dataSpeed: '0.9',
  },
  {
    id: 18,
    publicId: shuffledImagesPublicIds[17],
    alt: 'Gallery image 18',
    gridColumn: '1/2',
    gridRow: '24',
    aspectRatio: '1/1',
    dataSpeed: '1.1',
  },
  {
    id: 19,
    publicId: shuffledImagesPublicIds[18],
    alt: 'Gallery image 19',
    gridColumn: '2/4',
    gridRow: '25',
    aspectRatio: '2/1',
    dataSpeed: '1.2',
  },
  {
    id: 20,
    publicId: shuffledImagesPublicIds[19],
    alt: 'Gallery image 20',
    gridColumn: '3/4',
    gridRow: '26',
    aspectRatio: '1/1',
    dataSpeed: '0.8',
  },
  {
    id: 21,
    publicId: shuffledImagesPublicIds[20],
    alt: 'Gallery image 21',
    gridColumn: '1/3',
    gridRow: '28',
    aspectRatio: '1/1',
    dataSpeed: '1.0',
  },
  {
    id: 22,
    publicId: shuffledImagesPublicIds[21],
    alt: 'Gallery image 22',
    gridColumn: '2/4',
    gridRow: '29',
    aspectRatio: '2/1',
    dataSpeed: '0.9',
  },
  {
    id: 23,
    publicId: shuffledImagesPublicIds[22],
    alt: 'Gallery image 23',
    gridColumn: '1/2',
    gridRow: '30',
    aspectRatio: '1/1',
    dataSpeed: '1.1',
  },
  {
    id: 24,
    publicId: shuffledImagesPublicIds[23],
    alt: 'Gallery image 24',
    gridColumn: '2/4',
    gridRow: '32',
    aspectRatio: '2/1',
    dataSpeed: '1.2',
  },
  {
    id: 25,
    publicId: shuffledImagesPublicIds[24],
    alt: 'Gallery image 25',
    gridColumn: '3/4',
    gridRow: '33',
    aspectRatio: '1/1',
    dataSpeed: '0.8',
  },
  {
    id: 26,
    publicId: shuffledImagesPublicIds[25],
    alt: 'Gallery image 26',
    gridColumn: '1/3',
    gridRow: '34',
    aspectRatio: '1/1',
    dataSpeed: '1.0',
  },
  {
    id: 27,
    publicId: shuffledImagesPublicIds[26],
    alt: 'Gallery image 27',
    gridColumn: '3/4',
    gridRow: '36',
    aspectRatio: '1/1',
    dataSpeed: '0.9',
  },
  {
    id: 28,
    publicId: shuffledImagesPublicIds[27],
    alt: 'Gallery image 28',
    gridColumn: '1/4',
    gridRow: '37',
    aspectRatio: '3/1',
    dataSpeed: '1.1',
  },
  {
    id: 29,
    publicId: shuffledImagesPublicIds[28],
    alt: 'Gallery image 29',
    gridColumn: '2/3',
    gridRow: '38',
    aspectRatio: '1/1',
    dataSpeed: '1.2',
  },
  {
    id: 30,
    publicId: shuffledImagesPublicIds[29],
    alt: 'Gallery image 30',
    gridColumn: '3/4',
    gridRow: '40',
    aspectRatio: '1/1',
    dataSpeed: '0.8',
  },
  {
    id: 31,
    publicId: shuffledImagesPublicIds[30],
    alt: 'Gallery image 31',
    gridColumn: '1/3',
    gridRow: '41',
    aspectRatio: '2/1',
    dataSpeed: '1.0',
  },
  {
    id: 32,
    publicId: shuffledImagesPublicIds[31],
    alt: 'Gallery image 32',
    gridColumn: '3/4',
    gridRow: '42',
    aspectRatio: '1/1',
    dataSpeed: '0.9',
  },
  {
    id: 33,
    publicId: shuffledImagesPublicIds[32],
    alt: 'Gallery image 33',
    gridColumn: '1/2',
    gridRow: '44',
    aspectRatio: '1/1',
    dataSpeed: '1.1',
  },
  {
    id: 34,
    publicId: shuffledImagesPublicIds[33],
    alt: 'Gallery image 34',
    gridColumn: '2/4',
    gridRow: '45',
    aspectRatio: '2/1',
    dataSpeed: '1.2',
  },
  {
    id: 35,
    publicId: shuffledImagesPublicIds[34],
    alt: 'Gallery image 35',
    gridColumn: '3/4',
    gridRow: '46',
    aspectRatio: '1/1',
    dataSpeed: '0.8',
  },
  {
    id: 36,
    publicId: shuffledImagesPublicIds[35],
    alt: 'Gallery image 36',
    gridColumn: '1/3',
    gridRow: '48',
    aspectRatio: '1/1',
    dataSpeed: '1.0',
  },
  {
    id: 37,
    publicId: shuffledImagesPublicIds[36],
    alt: 'Gallery image 37',
    gridColumn: '2/4',
    gridRow: '49',
    aspectRatio: '2/1',
    dataSpeed: '0.9',
  },
  {
    id: 38,
    publicId: shuffledImagesPublicIds[37],
    alt: 'Gallery image 38',
    gridColumn: '1/2',
    gridRow: '50',
    aspectRatio: '1/1',
    dataSpeed: '1.1',
  },
  {
    id: 39,
    publicId: shuffledImagesPublicIds[38],
    alt: 'Gallery image 39',
    gridColumn: '2/4',
    gridRow: '52',
    aspectRatio: '2/1',
    dataSpeed: '1.2',
  },
  {
    id: 40,
    publicId: shuffledImagesPublicIds[39],
    alt: 'Gallery image 40',
    gridColumn: '3/4',
    gridRow: '53',
    aspectRatio: '1/1',
    dataSpeed: '0.8',
  },
  {
    id: 41,
    publicId: shuffledImagesPublicIds[40],
    alt: 'Gallery image 41',
    gridColumn: '1/3',
    gridRow: '54',
    aspectRatio: '1/1',
    dataSpeed: '1.0',
  },
  {
    id: 42,
    publicId: shuffledImagesPublicIds[41],
    alt: 'Gallery image 42',
    gridColumn: '3/4',
    gridRow: '56',
    aspectRatio: '1/1',
    dataSpeed: '0.9',
  },
  {
    id: 43,
    publicId: shuffledImagesPublicIds[42],
    alt: 'Gallery image 43',
    gridColumn: '1/4',
    gridRow: '57',
    aspectRatio: '3/1',
    dataSpeed: '1.1',
  },
  {
    id: 44,
    publicId: shuffledImagesPublicIds[43],
    alt: 'Gallery image 44',
    gridColumn: '2/3',
    gridRow: '58',
    aspectRatio: '1/1',
    dataSpeed: '1.2',
  },
  {
    id: 45,
    publicId: shuffledImagesPublicIds[44],
    alt: 'Gallery image 45',
    gridColumn: '3/4',
    gridRow: '60',
    aspectRatio: '1/1',
    dataSpeed: '0.8',
  },
  {
    id: 46,
    publicId: shuffledImagesPublicIds[45],
    alt: 'Gallery image 46',
    gridColumn: '1/3',
    gridRow: '61',
    aspectRatio: '2/1',
    dataSpeed: '1.0',
  },
  {
    id: 47,
    publicId: shuffledImagesPublicIds[46],
    alt: 'Gallery image 47',
    gridColumn: '3/4',
    gridRow: '62',
    aspectRatio: '1/1',
    dataSpeed: '0.9',
  },
  {
    id: 48,
    publicId: shuffledImagesPublicIds[47],
    alt: 'Gallery image 48',
    gridColumn: '1/2',
    gridRow: '64',
    aspectRatio: '1/1',
    dataSpeed: '1.1',
  },
  {
    id: 49,
    publicId: shuffledImagesPublicIds[48],
    alt: 'Gallery image 49',
    gridColumn: '2/4',
    gridRow: '65',
    aspectRatio: '2/1',
    dataSpeed: '1.2',
  },
  {
    id: 50,
    publicId: shuffledImagesPublicIds[49],
    alt: 'Gallery image 50',
    gridColumn: '3/4',
    gridRow: '66',
    aspectRatio: '1/1',
    dataSpeed: '0.8',
  },
  {
    id: 51,
    publicId: shuffledImagesPublicIds[50],
    alt: 'Gallery image 51',
    gridColumn: '1/3',
    gridRow: '68',
    aspectRatio: '1/1',
    dataSpeed: '1.0',
  },
  {
    id: 52,
    publicId: shuffledImagesPublicIds[51],
    alt: 'Gallery image 52',
    gridColumn: '2/4',
    gridRow: '69',
    aspectRatio: '2/1',
    dataSpeed: '0.9',
  },
  {
    id: 53,
    publicId: shuffledImagesPublicIds[52],
    alt: 'Gallery image 53',
    gridColumn: '1/2',
    gridRow: '70',
    aspectRatio: '1/1',
    dataSpeed: '1.1',
  },
  {
    id: 54,
    publicId: shuffledImagesPublicIds[53],
    alt: 'Gallery image 54',
    gridColumn: '2/4',
    gridRow: '72',
    aspectRatio: '2/1',
    dataSpeed: '1.2',
  },
  {
    id: 55,
    publicId: shuffledImagesPublicIds[54],
    alt: 'Gallery image 55',
    gridColumn: '3/4',
    gridRow: '73',
    aspectRatio: '1/1',
    dataSpeed: '0.8',
  },
  {
    id: 56,
    publicId: shuffledImagesPublicIds[55],
    alt: 'Gallery image 56',
    gridColumn: '1/3',
    gridRow: '74',
    aspectRatio: '1/1',
    dataSpeed: '1.0',
  },
  {
    id: 57,
    publicId: shuffledImagesPublicIds[56],
    alt: 'Gallery image 57',
    gridColumn: '3/4',
    gridRow: '76',
    aspectRatio: '1/1',
    dataSpeed: '0.9',
  },
  {
    id: 58,
    publicId: shuffledImagesPublicIds[57],
    alt: 'Gallery image 58',
    gridColumn: '1/4',
    gridRow: '77',
    aspectRatio: '3/1',
    dataSpeed: '1.1',
  },
  {
    id: 59,
    publicId: shuffledImagesPublicIds[58],
    alt: 'Gallery image 59',
    gridColumn: '2/3',
    gridRow: '78',
    aspectRatio: '1/1',
    dataSpeed: '1.2',
  },
  {
    id: 60,
    publicId: shuffledImagesPublicIds[59],
    alt: 'Gallery image 60',
    gridColumn: '3/4',
    gridRow: '80',
    aspectRatio: '1/1',
    dataSpeed: '0.8',
  },
  {
    id: 61,
    publicId: shuffledImagesPublicIds[60],
    alt: 'Gallery image 61',
    gridColumn: '1/3',
    gridRow: '81',
    aspectRatio: '2/1',
    dataSpeed: '1.0',
  },
  {
    id: 62,
    publicId: shuffledImagesPublicIds[61],
    alt: 'Gallery image 62',
    gridColumn: '3/4',
    gridRow: '82',
    aspectRatio: '1/1',
    dataSpeed: '0.9',
  },
  {
    id: 63,
    publicId: shuffledImagesPublicIds[62],
    alt: 'Gallery image 63',
    gridColumn: '1/2',
    gridRow: '84',
    aspectRatio: '1/1',
    dataSpeed: '1.1',
  },
  {
    id: 64,
    publicId: shuffledImagesPublicIds[63],
    alt: 'Gallery image 64',
    gridColumn: '2/4',
    gridRow: '85',
    aspectRatio: '2/1',
    dataSpeed: '1.2',
  },
  {
    id: 65,
    publicId: shuffledImagesPublicIds[64],
    alt: 'Gallery image 65',
    gridColumn: '3/4',
    gridRow: '86',
    aspectRatio: '1/1',
    dataSpeed: '0.8',
  },
  {
    id: 66,
    publicId: shuffledImagesPublicIds[65],
    alt: 'Gallery image 66',
    gridColumn: '1/3',
    gridRow: '88',
    aspectRatio: '1/1',
    dataSpeed: '1.0',
  },
  {
    id: 67,
    publicId: shuffledImagesPublicIds[66],
    alt: 'Gallery image 67',
    gridColumn: '2/4',
    gridRow: '89',
    aspectRatio: '2/1',
    dataSpeed: '0.9',
  },
  {
    id: 68,
    publicId: shuffledImagesPublicIds[67],
    alt: 'Gallery image 68',
    gridColumn: '1/2',
    gridRow: '90',
    aspectRatio: '1/1',
    dataSpeed: '1.1',
  },
  {
    id: 69,
    publicId: shuffledImagesPublicIds[68],
    alt: 'Gallery image 69',
    gridColumn: '2/4',
    gridRow: '92',
    aspectRatio: '2/1',
    dataSpeed: '1.2',
  },
  {
    id: 70,
    publicId: shuffledImagesPublicIds[69],
    alt: 'Gallery image 70',
    gridColumn: '3/4',
    gridRow: '93',
    aspectRatio: '1/1',
    dataSpeed: '0.8',
  },
  {
    id: 71,
    publicId: shuffledImagesPublicIds[70],
    alt: 'Gallery image 71',
    gridColumn: '1/3',
    gridRow: '94',
    aspectRatio: '1/1',
    dataSpeed: '1.0',
  },
  {
    id: 72,
    publicId: shuffledImagesPublicIds[71],
    alt: 'Gallery image 72',
    gridColumn: '3/4',
    gridRow: '96',
    aspectRatio: '1/1',
    dataSpeed: '0.9',
  },
  {
    id: 73,
    publicId: shuffledImagesPublicIds[72],
    alt: 'Gallery image 73',
    gridColumn: '1/4',
    gridRow: '97',
    aspectRatio: '3/1',
    dataSpeed: '1.1',
  },
  {
    id: 74,
    publicId: shuffledImagesPublicIds[73],
    alt: 'Gallery image 74',
    gridColumn: '2/3',
    gridRow: '98',
    aspectRatio: '1/1',
    dataSpeed: '1.2',
  },
  {
    id: 75,
    publicId: shuffledImagesPublicIds[74],
    alt: 'Gallery image 75',
    gridColumn: '3/4',
    gridRow: '100',
    aspectRatio: '1/1',
    dataSpeed: '0.8',
  },
  {
    id: 76,
    publicId: shuffledImagesPublicIds[75],
    alt: 'Gallery image 76',
    gridColumn: '1/3',
    gridRow: '101',
    aspectRatio: '2/1',
    dataSpeed: '1.0',
  },
  {
    id: 77,
    publicId: shuffledImagesPublicIds[76],
    alt: 'Gallery image 77',
    gridColumn: '3/4',
    gridRow: '102',
    aspectRatio: '1/1',
    dataSpeed: '0.9',
  },
  {
    id: 78,
    publicId: shuffledImagesPublicIds[77],
    alt: 'Gallery image 78',
    gridColumn: '1/2',
    gridRow: '104',
    aspectRatio: '1/1',
    dataSpeed: '1.1',
  },
  {
    id: 79,
    publicId: shuffledImagesPublicIds[78],
    alt: 'Gallery image 79',
    gridColumn: '2/4',
    gridRow: '105',
    aspectRatio: '2/1',
    dataSpeed: '1.2',
  },
  {
    id: 80,
    publicId: shuffledImagesPublicIds[79],
    alt: 'Gallery image 80',
    gridColumn: '3/4',
    gridRow: '106',
    aspectRatio: '1/1',
    dataSpeed: '0.8',
  },
  {
    id: 81,
    publicId: shuffledImagesPublicIds[0],
    alt: 'Gallery image 81',
    gridColumn: '1/3',
    gridRow: '108',
    aspectRatio: '1/1',
    dataSpeed: '1.0',
  },
  {
    id: 82,
    publicId: shuffledImagesPublicIds[1],
    alt: 'Gallery image 82',
    gridColumn: '2/4',
    gridRow: '109',
    aspectRatio: '2/1',
    dataSpeed: '0.9',
  },
  {
    id: 83,
    publicId: shuffledImagesPublicIds[2],
    alt: 'Gallery image 83',
    gridColumn: '1/2',
    gridRow: '110',
    aspectRatio: '1/1',
    dataSpeed: '1.1',
  },
  {
    id: 84,
    publicId: shuffledImagesPublicIds[3],
    alt: 'Gallery image 84',
    gridColumn: '2/4',
    gridRow: '112',
    aspectRatio: '2/1',
    dataSpeed: '1.2',
  },
];

// Helper function to paginate images
export function getPaginatedImages(page, limit, isMobile = false) {
  const start = (page - 1) * limit;
  const end = start + limit;
  const sourceArray = isMobile ? galleryImagesMobile : galleryImages;
  return sourceArray.slice(start, end);
}
